### ISSUE TITLE
why fork from veewee templates?

### ISSUE THREAD

**Issue by jedi4ever** [puppetlabs/puppet-vagrant-boxes#1]
Just curious why not just submit the changes to veewee templates?

I'm thinking of creating a gem plugin system for veewee templates. So you could have create a gem with puppetlabs-veewee or so? and have veewee pick up the templates when the gem is installed?

**Comment by kbarber** [comment]
They aren't forks, the purpose is just so we have a record of the canonical veewee definition used during creation if we ever need to create the same boxes again.
