### ISSUE TITLE
add support for augeas

### ISSUE THREAD

**Issue by jlgeering** [puppetlabs/puppet-vagrant-boxes#18]
Hi there,

The ubuntu box doesn't support augeas resources out of the box :-)

Just installing libaugeas-ruby doesn't help either, because there is a separate ruby for vagrant. Not sure how to fix it; probably link some libs into the vagrant ruby install?

**Comment by kbarber** [comment]
I believe this is a reasonable request +1.

**Comment by php-coder** [comment]
> Just installing libaugeas-ruby doesn't help either, because there is a separate ruby for vagrant.

BTW I overcome it by installing ruby-augeas from gem (this requires libaugeas-dev and pkg-config packages).

**Comment by globin** [comment]
+1

**Comment by jlgeering** [comment]
too old / expired / deceased / timed out / not relevant anymore / good bye
