### ISSUE TITLE
vagrant dependency is no more needed

### ISSUE THREAD

**Issue by jedi4ever** [puppetlabs/puppet-vagrant-boxes#2]
The vagrant gem will become deprecated.

Veewee - the one on github has export functionality without having to rely on vagrant.
`veewee vbox export basebox` will now work

**Comment by kbarber** [comment]
@jedi4ever - this is great news about veewee vbox export. Any chance of a gem release? See #2 ... I have a PR ready to at least remove the gem dependency based on your advice, but if you release a new gem I can really finish the job and add your new instructions to the README.md.

**Comment by kbarber** [comment]
I think we should leave this open until we get `veewee vbox export basebox` functionality in a new release of the veewee gem.

**Comment by kbarber** [comment]
This has been done, we just depend on the latest copy of veewee from github now.
